# Plots for paper
#quartz()
png("seaLevelChangeBrestNewlyn.png")
plot(tg_annual$newlyn$Year, tg_annual$newlyn$Height, type='l', col='blue', ylim=c(-120,210), ann=F, lwd=2)
lines(tg_annual$brest$Year, tg_annual$brest$Height, col='red')
lines(tg_annual$newlyn.lmRob$x[,2], tg_annual$newlyn.lmRob$fitted, col='blue', lty="dotted", lwd=2)
lines(tg_annual$newlyn1st.lmRob$x[,2], tg_annual$newlyn1st.lmRob$fitted, col='blue', lty="dotted", lwd=2)
lines(tg_annual$newlyn2nd.lmRob$x[,2], tg_annual$newlyn2nd.lmRob$fitted, col='blue', lty="dotted", lwd=2)
lines(tg_annual$newlyn3rd.lmRob$x[,2], tg_annual$newlyn3rd.lmRob$fitted, col='blue', lty="dashed", lwd=2)

lines(tg_annual$brest1916.lmRob$x[,2], tg_annual$brest1916.lmRob$fitted, col='red', lty="dotted", lwd=2)
lines(tg_annual$brest1st.lmRob$x[,2], tg_annual$brest1st.lmRob$fitted, col='red', lty="dotted", lwd=2)
lines(tg_annual$brest2nd.lmRob$x[,2], tg_annual$brest2nd.lmRob$fitted, col='red', lty="dotted", lwd=2)
lines(tg_annual$brest3rd.lmRob$x[,2], tg_annual$brest3rd.lmRob$fitted-10, col='red', lty="dashed", lwd=2)
#title(main="Sea level change at Brest and Newlyn", ylab="Sea Level [mm]", xlab="Year")
title(ylab="Sea Level [mm]", xlab="Year")
dev.off()

# Scatterplot of residuals
#x11()
#par(family="HersheySans")
png("scatterplotBrestNewlynMonthly19532008.png")
plot(tg_monthly$newlyn5308.lmRob$resid, tg_monthly$brest5308.lmRob$resid, type='p', ann=F, ylim=c(-200,300), xlim=c(-200,300))
title(xlab="Residual Sea Level at Newlyn [mm]", ylab="Residual Sea Level at Brest [mm]")
lines(c(-200,300),c(-200,300), col="black", lwd=2)
dev.off()

png("scatterplotBrestNewlynAnnual19532008.png")
plot(model3$tg.lmRob.newlynTotalP$resid, model3$tg.lmRob.brestTotalP$resid[as.integer(rownames(model3$tg.lmRob.newlynTotalP$x))], type='p', ann=F, ylim=c(-600,850), xlim=c(-600,850))
title(xlab="Residual Sea Level at Newlyn [mm]", ylab="Residual Sea Level at Brest [mm]")
lines(c(-600,850),c(-600,850), col="black", lwd=2)
dev.off()
# Plot of residuals after subtracting Brest from Newlyn
#x11()
#par(family="HersheySans")

png("scatterplotSubtractingBrestFromNewlyn.png")
plot(tg_monthly$mp.time, tg_monthly$mp.resid.diff, type='l', col='red')
#title("Plot of residuals after subtracting Brest from Newlyn")
title(xlab="Year", ylab="Residual [mm]")
dev.off()

# Model 1
plot(model1$time, model1$data.brest$msl, col='blue', ann=F)
points(model1$tg.lmRob.brest$x[,2], model1$tg.lmRob.brest$fitted, col='red')
lines(model1$time, model1$data.brest$msl, col='blue')
lines(model1$time, model1$tg.lmRob.brest$fitted, col='red')
#title(main="Brest", xlab="Year", ylab="Total Pressure [hPa]")
title(xlab="Year", ylab="Total Pressure [hPa]")

plot(model1$time, model1$data.newlyn$msl, col='blue', ann=F)
points(model1$tg.lmRob.newlyn$x[,2], model1$tg.lmRob.newlyn$fitted, col='red')
lines(model1$time, model1$data.newlyn$msl, col='blue')
lines(model1$tg.lmRob.newlyn$x[,2], model1$tg.lmRob.newlyn$fitted, col='red')
#title(main="Newlyn", xlab="Year", ylab="Total Pressure [hPa]")
title(xlab="Year", ylab="Total Pressure [hPa]")

# Model 2
png("model2-1960-1999.png")
split.screen(c(2,1))
screen(1)
plot(model2$time, model2$data.brest$msl, col='blue', ann=F)
points(model2$tg.lmRob.brest$x[,2], model2$tg.lmRob.brest$fitted, col='red')
lines(model2$time, model2$data.brest$msl, col='blue')
lines(model2$time, model2$tg.lmRob.brest$fitted, col='red')
#lines(model1$tg.lmRob.brest$x[,2], model1$tg.lmRob.brest$fitted, col='magenta')
#title(main="Model 2: Brest (HadSLP2r) 1960-1999", xlab="Year", ylab="Total Pressure [hPa]")
title(xlab="Year", ylab="Total Pressure [hPa]")

screen(2)
plot(model2$time, model2$data.newlyn$msl, col='blue', ann=F)
points(model2$tg.lmRob.newlyn$x[,2], model2$tg.lmRob.newlyn$fitted, col='red')
lines(model2$time, model2$data.newlyn$msl, col='blue')
lines(model2$tg.lmRob.newlyn$x[,2], model2$tg.lmRob.newlyn$fitted, col='red')
#lines(model1$tg.lmRob.newlyn$x[,2], model1$tg.lmRob.newlyn$fitted, col='magenta')
#title(main="Model 2: Newlyn (HadSLP2r) 1960-1999", xlab="Year", ylab="Total Pressure [hPa]")
title(xlab="Year", ylab="Total Pressure [hPa]")
close.screen(all = TRUE)
dev.off()

# Model 3
png("model3-1953-2008.png")
split.screen(c(2,1))
screen(1)
plot(model3$time, model3$data.brest$msl, col='blue', ann=F, ylim=c(0,2000))
points(model3$tg.lmRob.brest$x[,2], model3$tg.lmRob.brest$fitted, col='red')
lines(model3$time, model3$data.brest$msl, col='blue')
lines(model3$time, model3$tg.lmRob.brest$fitted, col='red')
#lines(model1$tg.lmRob.brest$x[,2], model1$tg.lmRob.brest$fitted, col='magenta')
#title(main="Model 3: Brest (HadSLP2r) 1953-2008", xlab="Year", ylab="Total Pressure [hPa]")
title(xlab="Year", ylab="Total Pressure [hPa]")

screen(2)
plot(model3$time, model3$data.newlyn$msl, col='blue', ann=F, ylim=c(900,3000))
points(model3$tg.lmRob.newlyn$x[,2], model3$tg.lmRob.newlyn$fitted, col='red')
lines(model3$time, model3$data.newlyn$msl, col='blue')
lines(model3$tg.lmRob.newlyn$x[,2], model3$tg.lmRob.newlyn$fitted, col='red')
#lines(model1$tg.lmRob.newlyn$x[,2], model1$tg.lmRob.newlyn$fitted, col='magenta')
#title(main="Model 3: Newlyn (HadSLP2r) 1953-1999", xlab="Year", ylab="Total Pressure [hPa]")
title(xlab="Year", ylab="Total Pressure [hPa]")
close.screen(all = TRUE)
dev.off()

# Model 4
png("model4-1916-1943.png")
split.screen(c(2,1))
screen(1)
plot(model4$time, model4$data.brest$msl, col='blue', ann=F, ylim=c(-300,1200))
points(model4$tg.lmRob.brest$x[,2], model4$tg.lmRob.brest$fitted, col='red')
lines(model4$time, model4$data.brest$msl, col='blue')
lines(model4$time, model4$tg.lmRob.brest$fitted, col='red')
#title(main="Model 4: Brest (HadSLP2r) 1916-1943", xlab="Year", ylab="Total Pressure [hPa]")
title(xlab="Year", ylab="Total Pressure [hPa]")

screen(2)
plot(model4$time, model4$data.newlyn$msl, col='blue', ann=F, ylim=c(400,1800))
points(model4$tg.lmRob.newlyn$x[,2], model4$tg.lmRob.newlyn$fitted, col='red')
lines(model4$time, model4$data.newlyn$msl, col='blue')
lines(model4$tg.lmRob.newlyn$x[,2], model4$tg.lmRob.newlyn$fitted, col='red')
#title(main="Model 4: Newlyn (HadSLP2r) 1916-1943", xlab="Year", ylab="Total Pressure [hPa]")
title(xlab="Year", ylab="Total Pressure [hPa]")
close.screen(all = TRUE)
dev.off()

# Model 5
png("model5-1916-2008.png")
split.screen(c(2,1))
screen(1)
plot(model5$time, model5$brestTotalP, lwd=2, ann=F, col='blue')
lines(model5$time, model5$brestTotalP, col='blue')
points(model5$tg.lmRob.brest$x[,2], model5$tg.lmRob.brest$fitted, col='red')
lines(model5$tg.lmRob.brest$x[,2], model5$tg.lmRob.brest$fitted, col='red')
lines(model5$time[38:93], model5$tg.lmRob.brest.partial$fitted, col='cyan', lwd=2)
lines(model5$time[1:37], model5$tg.lmRob.brest.pred$fit[1:37], col='orange', lwd=2)
#lines(model5$tg.lmRob.brest_22$x[,2], model5$tg.lmRob.brest_22$fitted, lty='dotted', col='red')
#title(main="Model 5: Brest (HadSLP2r) 1916-2008", xlab="Year", ylab="Total Pressure [hPa]")
title(xlab="Year", ylab="Sea level [mm]", main="Brest original data")
screen(2)
plot(model5$time, model5$newlynTotalP, lwd=2, ann=F, col='blue')
lines(model5$time, model5$newlynTotalP, lwd=2, col='blue')
points(model5$tg.lmRob.newlyn$x[,2], model5$tg.lmRob.newlyn$fitted, col='red')
lines(model5$tg.lmRob.newlyn$x[,2], model5$tg.lmRob.newlyn$fitted, col='red')
lines(model5$time[38:91], model5$tg.lmRob.newlyn.partial$fitted, col='cyan', lwd=2)
lines(model5$time[1:37], model5$tg.lmRob.newlyn.pred$fit[1:37], col='orange', lwd=2)
#title(main="Model 5: Newlyn (HadSLP2r) 1916-1999", xlab="Year", ylab="Total Pressure [hPa]")
title(xlab="Year", ylab="Sea level [mm]", main="Newlyn original data")
close.screen(all = TRUE)
dev.off()

# Brest_22
png("model5-1916-2008_Brest_22.png")
plot(model5$time, model5$brestTotalP_22, lwd=2, ann=F, col='blue')
lines(model5$time, model5$brestTotalP_22, col='blue')
points(model5$tg.lmRob.brest_22$x[,2], model5$tg.lmRob.brest_22$fitted, col='red')
lines(model5$tg.lmRob.brest_22$x[,2], model5$tg.lmRob.brest_22$fitted, col='red')
lines(model5$time[38:93], model5$tg.lmRob.brest.partial_22$fitted, col='cyan', lwd=2)
lines(model5$time[1:37], model5$tg.lmRob.brest.pred_22$fit[1:37], col='orange', lwd=2)
title(xlab="Year", ylab="Sea level [mm]", main="Brest data with 22mm subtracted 1916-1943")
dev.off()

# Map
png("mapOfPressureStations.png")
library(maps)
library(mapdata)
map("worldHires", xlim=c(-25,15), ylim=c(35,65), interior=F, fill=F, col="grey50", resolution=0)
map.axes()
points(expand.grid(c(-20, -15,-10, -5, 0 , 5, 10), c(40,45,50,55,60)), pch=19, col="grey20")
points( y=50.1, x=-5.55, pch='*', col="grey20", cex=3)
points( y=48.38, x=-4.5, pch='*', col="grey20", cex=3)
# Highlight points with a high correlation for Brest

dev.off()

# Rates
library(gplots)
png("ratesAndErrorBars.png")
plotCI(c(2.08,1.82,1.43),col='red', uiw=c(0.72,0.26,0.14), pch=c(21,22,23), ann=F,
       ylim=c(1,3.3), xaxt='n', xlim=c(-0,4))
plotCI(c(1.54,1.8, 1.71),col='blue', uiw=c(0.61,0.29,0.12), pch=c(21,22,23), add=T, ann=F)
text(1,3.1,"1916 - 1943", srt=90, cex=1.2, font=2)
text(2,2.5,"1953 - 2008", srt=90, cex=1.2, font=2)
text(3,2.2,"1916 - 2008", srt=90, cex=1.2, font=2)
title(ylab="Robust Standard Error [mm/yr]")
dev.off()

png("comparativePlotsBrest1888.png")
# Model 7
plot(model7$time, model7$data.brest$msl, lwd=2, ann=F)
points(model7$tg.lmRob.brest$x[,2], model7$tg.lmRob.brest$fitted, lty='dotdash')
lines(model7$time, model7$data.brest$msl, lwd=2)
lines(model7$tg.lmRob.brest$x[,2], model7$tg.lmRob.brest$fitted, lty='dotdash')
#title(main="Model 7: Brest (HadSLP2r) 1888-1943", xlab="Year", ylab="Total Pressure [hPa]")
title(xlab="Year", ylab="Total Pressure [hPa]")
dev.off()

# Acceleration?
png("brestAcceleration18502008.png")
plot(model8$tg.lmRob.brest$x[,2], model8$tg.lmRob.brest$resid, lwd=2, ann=F, col='red')
lines(model8$tg.lmRob.brest$x[,2], model8$tg.lmRob.brest$resid, lwd=2, ann=F, col='red')
points(model5$tg.lmRob.newlyn$x[,2], model5$tg.lmRob.newlyn$resid, lwd=2, col='blue')
lines(model5$tg.lmRob.newlyn$x[,2], model5$tg.lmRob.newlyn$resid, lwd=2, col='blue')
#title(main="Model 8: Brest Residuals (HadSLP2r) 1850-2008", xlab="Year", ylab="Total Pressure [hPa]")
title(xlab="Year", ylab="Total Pressure [hPa]")
dev.off()

# Douglas IB scaling?
png("brestIBnormalised18802008.png")
#plot(model9$pa.lmRob.brest$x[,2], model9$pa.scaled.brest, ann=F, type='l', lty='dashed', col='magenta')
plot(model9$pa.lmRob.brest$x[,2], model9$pa.norm.brest, ann=F, type='l', col='blue', lwd=2, ylim=c(-1.2,1.2))
lines(model9$tg.lmRob.brest$x[1:64,2], model9$tg.norm.brest[1:64], lwd=2, ann=F, type='l', col='red')
lines(model9$tg.lmRob.brest$x[65:120,2], model9$tg.norm.brest[65:120], lwd=2, col='red')
#title(main="Model 9: Brest Normalised and Scaled Residuals Compared with Pressure 1880-2008", xlab="Year", ylab="Normalised sea level")
title(xlab="Year", ylab="Normalised data")
dev.off()

png("brestIBscaling18802008.png")
plot(model9$pa.lmRob.brest$x[,2], (model9$pa.lmRob.brest$resid- mean(model9$pa.lmRob.brest$resid))*-10, type='l', col='blue', lwd=2, ann=F, ylim=c(-110,110))
lines(model9$tg.lmRob.brest$x[1:64,2], (model9$tg.lmRob.brest$resid[1:64]-mean(model9$tg.lmRob.brest$resid)), col='red', lwd=2)
lines(model9$tg.lmRob.brest$x[65:120,2], (model9$tg.lmRob.brest$resid[65:120]-mean(model9$tg.lmRob.brest$resid)), col='red', lwd=2)
lines(model9$pa.lmRob.brest$x[,2], (model9$pa.lmRob.brest$resid- mean(model9$pa.lmRob.brest$resid))*-10*3.6, type='l', col='magenta', lty='dashed')
lines(model9$pa.lmRob.brest$x[,2], (model9$pa.lmRob.brest$resid- mean(model9$pa.lmRob.brest$resid))*-10*1.84, type='l', col='magenta', lwd=2)
title(xlab="Year", ylab="Sea Level [mm]")
dev.off()

# Douglas IB scaling CRU?
png("brestIBnormalisedCRU18802000.png")
#plot(model12$pa.lmRob.brest$x[,2], model12$pa.scaled.brest, ann=F, type='l', lty='dashed', col='magenta')
plot(model12$pa.lmRob.brest$x[,2], model12$pa.norm.brest, ann=F, type='l', col='blue', lwd=2, ylim=c(-1.2,1.2))
lines(model12$tg.lmRob.brest$x[1:64,2], model12$tg.norm.brest[1:64], lwd=2, ann=F, type='l', col='red')
lines(model12$tg.lmRob.brest$x[65:120,2], model12$tg.norm.brest[65:120], lwd=2, col='red')
#title(main="Model 9: Brest Normalised and Scaled Residuals Compared with Pressure 1880-2008", xlab="Year", ylab="Normalised sea level")
title(xlab="Year", ylab="Normalised data")
dev.off()

png("brestIBscalingCRU18802000.png")
plot(model12$pa.lmRob.brest$x[,2], (model12$pa.lmRob.brest$resid- mean(model12$pa.lmRob.brest$resid))*-10, type='l', col='blue', lwd=2, ann=F, ylim=c(-110,110))
lines(model12$tg.lmRob.brest$x[1:64,2], (model12$tg.lmRob.brest$resid[1:64]-mean(model12$tg.lmRob.brest$resid)), col='red', lwd=2)
lines(model12$tg.lmRob.brest$x[65:120,2], (model12$tg.lmRob.brest$resid[65:120]-mean(model12$tg.lmRob.brest$resid)), col='red', lwd=2)
lines(model12$pa.lmRob.brest$x[,2], (model12$pa.lmRob.brest$resid- mean(model12$pa.lmRob.brest$resid))*-10*3.6, type='l', col='magenta', lty='dashed')
lines(model12$pa.lmRob.brest$x[,2], (model12$pa.lmRob.brest$resid- mean(model12$pa.lmRob.brest$resid))*-10*1.84, type='l', col='magenta', lwd=2)
title(xlab="Year", ylab="Sea Level [mm]")
dev.off()

# Residuals
png('BrestResiduals.png')
plot(model5$time[38:93], model5$brestTotalP[38:93] - model5$tg.lmRob.brest.partial$fitted, col='cyan', lwd=2, type='l', xlim=c(1916,2008), ylim=c(-600,600), xlab='Year', ylab='Brest Residuals [Pa]', main="Brest and Brest_22 data minus fit and prediction")
lines(model5$time[1:37], model5$brestTotalP[1:37] - model5$tg.lmRob.brest.pred$fit[1:37], col='orange', lwd=2)
lines(model5$time[38:93], model5$brestTotalP_22[38:93] - model5$tg.lmRob.brest.partial_22$fitted, col='blue', lty='dotdash')
lines(model5$time[1:37], model5$brestTotalP_22[1:37] - model5$tg.lmRob.brest.pred_22$fit[1:37], col='magenta', lwd=2)
legend(1950,600, c('Brest Fit Residuals', 'Brest Prediction Residuals', 'Brest_22 Fit Residuals', 'Brest_22 Prediction Residuals'), col=c('cyan','orange', 'blue','magenta'), lwd=c(2,2,1,2), lty=c(1,1,4,1))
grid(lwd=2)
dev.off()

png('NewlynResiduals.png')
plot(model5$time[38:91], model5$newlynTotalP[38:91] - model5$tg.lmRob.newlyn.partial$fitted, col='cyan', lwd=2, type='l', xlim=c(1916,2008), ylim=c(-600,600), xlab='Year', ylab='Newlyn Residuals [Pa]', main="Newlyn data minus fit and prediction")
lines(model5$time[1:37], model5$newlynTotalP[1:37] - model5$tg.lmRob.newlyn.pred$fit[1:37], col='orange', lwd=2)
legend(1950,600, c('Newlyn Fit Residuals', 'Newlyn Prediction Residuals'), col=c('cyan','orange'), lwd=c(2,2), lty=c(1,1))
grid(lwd=2)
dev.off()

png('delfzijl_fit.png')
plot(model5$time[1:92], model5$delfzijlTotalP, lwd=2, ann=F, col='blue', type='b', xlim=c(1916,2008), ylim=c(-10, 3000))
title(xlab='Year', ylab='Delfzijl [Pa]', main="Delfzijl original data")
lines(model5$time[1:92], model5$tg.lmRob.delfzijl$fitted, col='red', type='b')
lines(model5$time[38:92], model5$tg.lmRob.delfzijl.partial$fitted, col='cyan', lwd=2)
lines(model5$time[1:37], model5$tg.lmRob.delfzijl.pred$fit[1:37], col='orange', lwd=2)
grid(lwd=2)
dev.off()

png('DelfzijlResiduals.png')
plot(model5$time[38:93], model5$delfzijlTotalP[38:93] - model5$tg.lmRob.delfzijl.partial$fitted, col='cyan', lwd=2, type='l', xlim=c(1916,2008), ylim=c(-600,600), xlab='Year', ylab='Delfzijl Residuals [Pa]', main="Delfzijl data minus fit and prediction")
lines(model5$time[1:37], model5$delfzijlTotalP[1:37] - model5$tg.lmRob.delfzijl.pred$fit[1:37], col='orange', lwd=2)
legend(1950,600, c('Delfzijl Fit Residuals', 'Delfzijl Prediction Residuals'), col=c('cyan','orange'), lwd=c(2,2), lty=c(1,1))
grid(lwd=2)
dev.off()
